### ISSUE TITLE
BUG：使用提供的默认配置无法启动

### ISSUE THREAD

**Issue by d-w-x** [kratos-rebirth/quickstart#6]
配置问题点：
```yaml
# 分享组件设置
share:
  enable: true
  title: "分享这一刻"
  message: "让朋友们也来瞅瞅！"
  platforms:
    - name: "喵窝"
      # 这一行
      html: <svg fill="currentColor" width="18" height="18" viewBox="0 0 329 388"><path d="M0,36.226c0,-19.993 16.233,-36.226 36.226,-36.226c13.788,0 25.787,7.719 31.908,19.068l188.366,229.845l0,-111.259c-6.356,5.508 -14.645,8.843 -23.707,8.843c-19.994,0 -36.226,-16.232 -36.226,-36.226c-0,-8.551 2.968,-16.413 7.93,-22.613l-0.015,-0.013l56.614,-69.08c6.2,-11.073 18.047,-18.565 31.63,-18.565c19.994,0 36.227,16.233 36.227,36.226l-0,314.644c-0,19.994 -16.233,36.226 -36.227,36.226c-13.166,0 -24.701,-7.039 -31.044,-17.555l-189.229,-230.899l-0,212.228c-0,19.994 -16.233,36.226 -36.227,36.226c-19.993,0 -36.226,-16.232 -36.226,-36.226l0,-314.644Z" /></svg>
      color: "#62b6e7"
      link: "https://nya.one/share?text=%3E%20$TITLE%0A%3E%0A%3E%20$SUMMARY%0A----%20$SITE%0A%0A$URL"
```

报错：
```text
\node_modules\hexo-theme-kratos-rebirth\layout\_modals\share.ejs:19
    17|                 <% for (const platform of theme.share.platforms) { %>
    18|                     <button class="kr-share-platform-button" style="color: <%- platform.color %>;" title="<%- platform.name %>" onclick="krShareModalOpenPlatform('<%- platform.link %>')">
 >> 19|                         <%- icon_to_html(platform.icon) %>
    20|                     </button>
    21|                 <% } %>
    22|             </div>

Cannot read properties of undefined (reading 'includes')
    at Object.<anonymous> (\node_modules\hexo-theme-kratos-rebirth\scripts\icon-to-html.js:2:9)
    at eval ("node_modules\hexo-theme-kratos-rebirth\layout\_modals\share.ejs":28:17)
```

参考修复：将 icon 的 `html` 更换为 `icon`

---

评论：
1. 没想到真有喵窝友友想直接保留这个配置吧！
2. 可能这个项目也需要加个自动化部署个demo页面确保可用性？初始化项目运行即报错可能体验有点糟糕。
3. 要是能把微博、QQ、朋友圈等国内常见媒体的share都加上最好了，当然没有自己搜也行。
